ISLANDORA-1869
Islandora/islandora_solution_pack_compound pull request #109
Opened 2016-12-08 06:03 UTC by jonathangreen

**JIRA Ticket**: 

https://jira.duraspace.org/browse/ISLANDORA-1869

# What does this Pull Request do?

Adds three new PHP targets for Travis:
* 5.6
* 7.0
* 7.1

# What's new?

Drupal 7 mostly is support PHP 7
https://www.drupal.org/node/2656548
and Ubuntu 16.04 comes with PHP 7 so if we can we should see if Islandora will pass tests with against these new versions of PHP. 

# Additional Notes:

This should get discussed before it is merged, I just wanted to make pull requests against the core modules to see what passes and what fails.

# Interested parties
@Islandora/7-x-1-x-committers

2016-12-14 16:12 UTC, DonRichards requested changes
This includes functionality not included or commented on in the description. You'll need to explain this in more detail. Rewriting blocks for compound objects isn't commented in the description. Were these pushed by mistake?

2016-12-14 16:17 UTC, jonathangreen commented
Sorry about that. I wrote a script to make these pull requests, since it had to go into all the islandora repositories. I guess this one started out on the branch for #107. Fixed now.

2016-12-15 19:31 UTC, DonRichards approved these changes

2016-12-15 21:04 UTC, dannylamb approved these changes

2016-12-15 21:04 UTC, merged