ISLANDORA-2072 removed the ORDER BY from RI query and added sort nume…
Islandora/islandora_solution_pack_compound pull request #134
Opened 2017-10-07 22:13 UTC by whikloj

…rically routine

**JIRA Ticket**: https://jira.duraspace.org/browse/ISLANDORA-2059

# What does this Pull Request do?

Ensure values are sorted numerically in both Sparql queries.

# How should this be tested?

You can't seem to use Mulgara for this, so you'll need a different triplestore. 

According to the ticket.

With the non-legacy SPARQL option enabled for "Compound Member Query", when the sequence gets over 1 digit the string sort doesn't work.
eg:
1
10
11
12
2
3

Example:
* Does this change require documentation to be updated? no
* Does this change add any new dependencies?  no
* Does this change require any other modifications to be made to the repository (ie. Regeneration activity, etc.)?  no
* Could this change impact execution of existing code? no

# Interested parties
@nhart

2017-10-11 14:55 UTC, DiegoPino commented
@whikloj this one needs some DCS review/recheck. Seems to be failing on 5.3, 5.5 and 7.1 but not inbetween...mmmm

2017-10-11 14:57 UTC, DiegoPino requested changes
Just minor DCS. I only commented on the first one, but seems like phpcs is detecting a few more

2017-10-11 14:57 UTC, DiegoPino commented on includes/backends.inc
> +  // Removed the ORDER BY from the SPARQL query so that the values are sorted sequentially
more than 80 chars here

2017-10-12 00:17 UTC, whikloj commented
@DiegoPino updated

2017-10-12 17:40 UTC, DiegoPino approved these changes

2017-10-12 17:44 UTC, DiegoPino commented
@whikloj ok, thanks, looks good. Need to test but looks good. I have a question in the meanwhile. Does this adds actually processing time? i would guess removing the order by from SPARQL should inmediatelly reduce query time, but not sure how much extra in the sort function of php is added. Do you have/anyone have a real case use where the number of children is like "HUGE?"
Lastly, if we know that mulgara handles this a strings, could we maybe use "deliverately" strings in the  predicate? instead of 1 maybe "0001", etc? As a corrective, future fix?

2017-10-12 19:06 UTC, whikloj commented
@DiegoPino I don't know of anyone with huge compounds. Maybe @jonathangreen?

If we are going to set them as strings, I would prefer to set them as integers. The major problem is fixing all the existing triples in the existing triplestores. That could be a huge pain.

2017-10-12 19:09 UTC, DiegoPino commented
I agree. Updating all is a pain. I prefer xsd:integer also. Will give this 24hrs for now. After your explanation(i had where it was working and where not wrong) This seems like an improvement not a bug report because we never tested against anything different than mulgara and it works in mulgara. But your solution is fine. We can still revisit the XSD idea without affecting this pull

2017-10-12 19:33 UTC, jonathangreen commented
I'd like to test this with my huge compounds before this gets merged, I don't really like the idea of moving the sort to PHP instead of in the triple store, but I'll see if it slows down my compound loads. 

As I remember, I added the sort to the SPARQL query here, and doing the query on the SPARQL side speeded up my load time for very large compounds, which is why I did it.

2017-10-12 19:36 UTC, DiegoPino commented
@jonathangreen ok, will stand by. Then doing the xsd:integer piece should/could be a corrective/future fix for non mulgaras?

2017-10-12 19:39 UTC, jonathangreen commented
@DiegoPino yes. I think changing the datatype to an integer is the right way to fix this problem, even if it means a data migration. Anything else is really a workaround.

2017-10-12 19:55 UTC, jonathangreen commented
My SPARQL-fu isn't always that strong, but would something like this fix it without moving the sort to PHP? 
 
```sparql
 PREFIX islandora-rels-ext: <http://islandora.ca/ontology/relsext#>
 PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
 SELECT DISTINCT ?object ?title ?seq
 FROM <#ri>
 WHERE {
   ?object <fedora-model:label> ?title ;
           <fedora-rels-ext:$rels_predicate> <info:fedora/$pid> .
   OPTIONAL {
       ?object islandora-rels-ext:isSequenceNumberOf$escaped_pid ?seq
   }
   OPTIONAL {{
       ?object islandora-rels-ext:isViewableByRole ?role
     } UNION {
       ?object islandora-rels-ext:isViewableByUser ?user
   }}
    FILTER((!bound(?role) && !bound(?user)) || (bound(?user) && ?user='{$user_name}') || (bound(?role) && ($role_matcher)))
    $namespace_filter
  }
 ORDER BY ASC(xsd:integer(?seq))
```

2017-10-12 19:56 UTC, jonathangreen commented
Just tried it on mulgara and that query gives:
`org.mulgara.parser.MulgaraParserException: Unable to support arbitrarily complex ORDER BY clauses.`

I feel like it would probably fix it when using blazegraph though.

2017-10-12 19:57 UTC, DiegoPino commented
@jonathangreen looks sweet, does that actually work in the Mulgara interface? not sure..

2017-10-12 19:57 UTC, DiegoPino commented
@jonathangreen ups, jinx!

2017-10-12 20:01 UTC, jonathangreen commented
If that fixes it using blazegraph, maybe we could have an option for it? Anyone have a blaze graph with some compounds handy to test with?

2017-10-13 15:09 UTC, whikloj commented
Confirmed that @jonathangreen's SPARQL works in Blazegraph.

2017-10-13 15:13 UTC, whikloj commented
So how do we word this? 
`If you are using a SPARQL compliant triplestore (and Mulgara is NOT compliant). Check this box for quick correct sorting of compound children.`

2017-10-13 15:18 UTC, DiegoPino commented
@whikloj @jonathangreen so, wording seems ok but just to avoid making again something platform specific can anyone make any test with a type casted ordering on Fuseki? Does not need to be this exact sparql query (means no need to mount a fedora 3 repo with fuseki), just any query to make sure ordering by type casted value/piece works. Are we also going to fix for the future? by explicitly adding xsd:integer to the value for new objects's predicates? Any comments on that? lastly. Do we have this issue in any other SP? what about books?

2017-10-13 15:21 UTC, jonathangreen commented
@adam-vessey has much SPARQL-fu. @adam-vessey any ideas for a query that might work in both blazegraph and mulgara? The query I posted above was the best I could come up with.

2017-10-13 17:34 UTC, adam-vessey commented
@jonathangreen: Nah, not really. Mulgara has a "let" dealio to permit assignment which might let it work; however, it doesn't appear to be standard... Sparql 1.1/Blazegraph instead has "bind" for assignment...

Mulgara's "LET" would look something like (not 100% sure if it would even work):
```
SELECT [...]
WHERE {
[...]
LET(?sequence := xsd:integer(?seq))
}
ORDER BY ASC(?sequence)
```

... but would need some mechanism to make it adjust the query appropriately for each... Sparql 1.1 stuff could go a few different places, casting in the select clause, or in the order by, or via bind or whatnot...

... ideally, we should just use typed literals to avoid the necessity for casting, but... could be some big batches to roll over existing objects to typify them.

2017-10-20 00:36 UTC, DiegoPino requested changes
In discussion so putting in red until we figure out

2017-10-23 09:36 UTC, lucasvanschaik commented on includes/backends.inc
> +  $sort = function($a, $b) {
Same sort function as on line 34, should be a named function?

2017-10-23 09:41 UTC, lucasvanschaik commented on includes/backends.inc
>      $sort = function($a, $b) {
function `intval` does not return empty values (only 0 on error), so why check for empty values?
Also, why check for equality (`if ($a === $b) { return 0; }`) when `return $a - $b` accomplishes the same.
Question: is it possible that `$a['seq']['value']` does not exist? If so, shouldn't it be checked to silence warnings?

2017-12-11 22:57 UTC, whikloj commented
Coming back around to this and wondering from the assembled watchers. 

If I create a Drupal cron worker to eat away at a queue, then create a drush command that populates that queue with objects that have an `isConstituentOf` predicate? 

The worker would do a query, SPARQL DELETE {} INSERT {} WHERE {} to update the `isSequenceNumberOf$escaped_pid` field.

Last thing would be to ensure that we are properly "typifying" the `isSequenceNumberOf$escaped_pid` field for all new objects going in

Or is that too slow of a process for this action and we want it to all happen before you add any new items to a repo?

2018-11-26 18:38 UTC, jonathangreen commented
I'm bringing this PR back to life to see if we can find a resolution here. I'm having this issue as well.

2018-11-26 18:51 UTC, jonathangreen commented
Some discussion from IRC: 
https://logs.woh.ca/islandora/2018-11-26#1543256721-1543258147;

2018-11-26 18:51 UTC, jonathangreen commented
As per that discussion, I am closing this PR and issuing a new one.

2018-11-26 18:51 UTC, closed without merging